version: '3'

services:
  web1:
    build: .
    image: go_app:latest
    container_name: go_app
    restart: always
    command: go run final.go
    ports:
      - "8080:8080"
  web2:
    image: go_app:latest
    container_name: go_app_save
    restart: always
    command: go run save.go
    ports:
      - "8081:8081"
